### ISSUE TITLE
【提问】如何解决切换模型需重启前后端的问题

### ISSUE THREAD

**Issue by yann0917** [X-T-E-R/TTS-for-GPT-soVITS#16]
如何解决切换模型需重启前后端的问题。也就是如何实现动态切换模型？

**Comment by X-T-E-R** [comment]
已解决，用api接口的http://127.0.0.1:5000/character_list

就会重新扫描项目文件夹

文档  https://www.yuque.com/xter/zibxlp/knu8p82lb5ipufqy
