### ISSUE TITLE
Linux cpu 环境，源码缺失 tts_pipline

### ISSUE THREAD

**Issue by fxconfig** [X-T-E-R/TTS-for-GPT-soVITS#18]
from TTS_infer_pack.TTS import TTS, TTS_Config

**Comment by X-T-E-R** [comment]
hello , It's based on [https://github.com/RVC-Boss/GPT-SoVITS/tree/fast_inference_](https://github.com/RVC-Boss/GPT-SoVITS/tree/fast_inference_) now

you could just use my fork : 
https://github.com/X-T-E-R/GPT-SoVITS-Inference

哦你说的是中文啊
就是我现在用的是原始项目的beta分支，你直接装我fork的就好了
