### ISSUE TITLE
python版本推理

### ISSUE THREAD

**Issue by sun-rabbit** [X-T-E-R/TTS-for-GPT-soVITS#20]
老师是否以后会出python版本呢直接传入text就能合成音频

**Comment by X-T-E-R** [comment]
啊？网址链接不是传入text就返回音频吗

**Comment by sun-rabbit** [comment]
> 啊？网址链接不是传入text就返回音频吗

啊，不好意思，我没有表达明白，我做了一个语音交互，智能对话机器人，不过用的科大讯飞的超拟人语音合成，我想测试一下sovits的语音合成，请问有没有不是网页版的呀（实在没有我去巴拉巴拉代码看看函数）

**Comment by X-T-E-R** [comment]
> > 啊？网址链接不是传入text就返回音频吗
> 
> 啊，不好意思，我没有表达明白，我做了一个语音交互，智能对话机器人，不过用的科大讯飞的超拟人语音合成，我想测试一下sovits的语音合成，请问有没有不是网页版的呀（实在没有我去巴拉巴拉代码看看函数）

不是，你只要类似`http://127.0.0.1:5000/tts?text=你好` 这样就可以合成音频了（在后端开着的情况下），否则就需要使用更加底层的函数，比如我在load_…….py里面有一个get_tts_wav_api

**Comment by sun-rabbit** [comment]
> > > 啊？网址链接不是传入text就返回音频吗
> > 
> > 
> > 啊，不好意思，我没有表达明白，我做了一个语音交互，智能对话机器人，不过用的科大讯飞的超拟人语音合成，我想测试一下sovits的语音合成，请问有没有不是网页版的呀（实在没有我去巴拉巴拉代码看看函数）
> 
> https://github.com/jmaple12/speech_to_speech/blob/main/LargeModel/Speech_Synthesis/GPT_Sovits/inference_maple0306fix.py 我这里有一个官方0306fix版本根据inference_webui.py改的，把文件里面第16行的路径变量改为根目录所在绝对路径就可以了，调用最后的handle函数就可以使用了。（自己使用得下载很多扩展包）

非常感谢大佬的帮助，稍后我跑一下代码，祝你生活愉快
