### ISSUE TITLE
Flask 模块问题

### ISSUE THREAD

**Issue by xiaocunjie** [X-T-E-R/TTS-for-GPT-soVITS#3]
这是我安装的flask：
PS D:\SSDOWN\TTS-for-GPT-soVITS-main> pip3 show flask
Name: Flask
Version: 2.1.2
Summary: A simple framework for building complex web applications.
Home-page: https://palletsprojects.com/p/flask
Author: Armin Ronacher
Author-email: armin.ronacher@active-4.com
License: BSD-3-Clause
Location: D:\program\python\Lib\site-packages
Requires: click, itsdangerous, Jinja2, Werkzeug
Required-by:
但是运行后显示：
Traceback (most recent call last):
  File "D:\SSDOWN\GPT-SoVITS-0211\TTS-for-GPT-soVITS\tts_backend.py", line 2, in <module>
    from flask import Flask, request, Response, jsonify
ModuleNotFoundError: No module named 'flask'
我只安装了Python3：
Python 3.12.0 (tags/v3.12.0:0fb18b0, Oct  2 2023, 13:03:39) [MSC v.1935 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
大佬能解答一下吗？

**Comment by xiaocunjie** [comment]
卸载重装也好几次了

**Comment by X-T-E-R** [comment]
这是一个env问题，就是说你只能用./runtime/Scripts/pip.exe装才是装到了这个虚拟环境下

**Comment by xiaocunjie** [comment]
明白了，谢谢

**Comment by X-T-E-R** [comment]
现已推出整合包，直接装整合包可以解决很多问题
