### ISSUE TITLE
角色选择bug

### ISSUE THREAD

**Issue by Tomiya233** [X-T-E-R/TTS-for-GPT-soVITS#6]
当post请求中设置非默认角色时，或使用默认角色的参考文本进行推理，导致除了默认角色外均无法正常生成音频

如下，默认角色为dingzhen
![image](https://github.com/X-T-E-R/TTS-for-GPT-soVITS/assets/85816199/a439bebf-3ae8-4bd5-b483-bc28e6b4de8a)
![image](https://github.com/X-T-E-R/TTS-for-GPT-soVITS/assets/85816199/46465c7c-bc06-4bfb-a71b-044f72cac493)

**Comment by X-T-E-R** [comment]
已修正，是未设置全局变量的原因
